name: greenhome
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  image_picker: ^1.0.7
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/images/
    - asset/images/icon/
    - .env

http: ^0.13.5 # or the latest version
